In [1]:
#Import Pandas
import pandas as pd

The chosen dataset for this project was the first option in the 2018 Tidy Tuesday's Datasets. It can be found here: https://github.com/rfordatascience/tidytuesday/blob/master/data/2018/2018-04-02/us_avg_tuition.xlsx?raw=true

In order to apply pre-processing in pandas to this dataset, I needed to read it into a dataframe as an excel document then convert it to a CSV, then read that CSV file into a dataframe.

In [2]:
df = pd.read_excel("us_avg_tuition.xlsx")

In [3]:
df.to_csv("us_avg_tuition.csv")

In [4]:
df = pd.read_csv("us_avg_tuition.csv", index_col=False)

In [6]:
df.head(10)

,Unnamed: 0,State,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16
0,0,Alabama,5682.838120,5840.549785,5753.496432,6008.168872,6475.091706,7188.954303,8071.133759,8451.902223,9098.069156,9358.928842,9496.084106,9751.101349
1,1,Alaska,4328.281362,4632.623449,4918.500619,5069.822132,5075.482406,5454.606610,5759.152951,5762.420526,6026.142669,6012.444735,6148.808010,6571.340317
2,2,Arizona,5138.495312,5415.516049,5481.419145,5681.637955,6058.463821,7263.204332,8839.604653,9966.716345,10133.503178,10296.199709,10413.843882,10646.278352
3,3,Arkansas,5772.301869,6082.379324,6231.977179,6414.900365,6416.503410,6627.092143,6900.912413,7028.991050,7286.580461,7408.495063,7606.410008,7867.296736
4,4,California,5285.921489,5527.881290,5334.825779,5672.472175,5897.888491,7258.771494,8193.738802,9436.425766,9360.573556,9274.193266,9186.824330,9269.844227
5,5,Colorado,4703.777096,5406.966520,5596.348344,6227.001872,6284.137259,6948.472865,7748.200834,8315.632333,8792.855707,9292.953578,9298.598732,9748.187716
6,6,Connecticut,7983.694530,8249.074289,8367.549337,8677.702333,8720.976396,9371.018588,9827.013123,9736.430795,10036.626554,10453.110455,10663.995408,11397.336553
7,7,Delaware,8352.890000,8610.597236,8681.845514,8945.801402,8995.473414,9987.183008,10534.181495,11026.241145,11362.690446,11502.523759,11514.659801,11676.215597
8,8,Florida,3848.201246,3924.233889,3887.656069,3879.416438,4150.004319,4783.031720,5510.658802,5940.944645,6494.900526,6451.664429,6344.999755,6360.159309
9,9,Georgia,4298.040095,4492.166899,4584.267744,4790.265838,4831.364505,5549.912617,6428.007247,7709.284142,7853.256626,7992.389604,8063.014195,8446.961426

As we can see above, there is an additional id column that we do not need so we will remove that.

In [7]:
df = df.drop("Unnamed: 0", axis=1)

In [8]:
df.set_index("State")

,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16
State,,,,,,,,,,,,
Alabama,5682.838120,5840.549785,5753.496432,6008.168872,6475.091706,7188.954303,8071.133759,8451.902223,9098.069156,9358.928842,9496.084106,9751.101349
Alaska,4328.281362,4632.623449,4918.500619,5069.822132,5075.482406,5454.606610,5759.152951,5762.420526,6026.142669,6012.444735,6148.808010,6571.340317
Arizona,5138.495312,5415.516049,5481.419145,5681.637955,6058.463821,7263.204332,8839.604653,9966.716345,10133.503178,10296.199709,10413.843882,10646.278352
Arkansas,5772.301869,6082.379324,6231.977179,6414.900365,6416.503410,6627.092143,6900.912413,7028.991050,7286.580461,7408.495063,7606.410008,7867.296736
California,5285.921489,5527.881290,5334.825779,5672.472175,5897.888491,7258.771494,8193.738802,9436.425766,9360.573556,9274.193266,9186.824330,9269.844227
Colorado,4703.777096,5406.966520,5596.348344,6227.001872,6284.137259,6948.472865,7748.200834,8315.632333,8792.855707,9292.953578,9298.598732,9748.187716
Connecticut,7983.694530,8249.074289,8367.549337,8677.702333,8720.976396,9371.018588,9827.013123,9736.430795,10036.626554,10453.110455,10663.995408,11397.336553
Delaware,8352.890000,8610.597236,8681.845514,8945.801402,8995.473414,9987.183008,10534.181495,11026.241145,11362.690446,11502.523759,11514.659801,11676.215597
Florida,3848.201246,3924.233889,3887.656069,3879.416438,4150.004319,4783.031720,5510.658802,5940.944645,6494.900526,6451.664429,6344.999755,6360.159309
Georgia,4298.040095,4492.166899,4584.267744,4790.265838,4831.364505,5549.912617,6428.007247,7709.284142,7853.256626,7992.389604,8063.014195,8446.961426
Hawaii,4266.538775,4263.772334,4957.201268,5748.089861,6317.771281,7356.293920,8164.182229,8839.584777,8972.025377,9269.589848,9712.779264,10174.733720
Idaho,4524.849599,4790.179058,4873.936236,5020.556063,5003.874489,5414.711072,5834.686415,6002.213277,6238.646231,6462.257950,6609.709179,6818.470344
Illinois,8182.782872,8444.492098,9449.994752,10424.929169,10872.468831,11536.459733,12007.631386,12285.417179,12675.212445,12852.833103,12812.552602,13189.100826
Indiana,7367.528712,7517.478864,7687.356118,7876.842295,7835.642141,8470.044355,8744.366807,8813.175884,9078.277158,9118.778418,9048.660744,9119.648546
Iowa,6813.105480,6862.829202,6919.206880,7124.102602,6979.602035,7438.301415,7832.491801,7988.162056,8157.428391,8007.194294,7868.433512,7877.344019
Kansas,5345.143970,5739.176796,6113.529740,6583.321575,6520.660381,6995.017660,7254.496599,7309.981675,7583.460437,7896.354244,8270.389996,8530.493831
Kentucky,5639.996325,6142.226029,6759.713297,7193.991675,7387.550172,7886.018008,8230.958190,8423.380618,8814.731074,8888.902469,9223.341423,9566.672573
Louisiana,4453.026589,4512.930041,4421.255921,4388.117235,4419.076494,4745.352601,5181.157749,5541.642177,6119.894240,6748.433251,7336.703233,7870.959723
Maine,7057.555723,7407.556346,7758.893681,8402.728929,8764.375134,9468.541014,9791.983111,9893.827799,9753.288472,9594.341145,9560.244160,9572.968445
Maryland,8530.557445,8716.855670,8462.541838,8379.814479,8020.086778,8284.973388,8469.600149,8409.647994,8552.226674,8663.288033,8696.807032,9163.291582
Massachusetts,8863.211383,8958.685210,8892.939961,9036.313481,8939.055054,10238.746539,10386.398631,10737.856030,11092.894258,10980.558205,10986.923867,11588.125344
Michigan,7930.772313,8668.001218,8998.487184,9737.495660,9905.761943,10817.231840,11094.661691,11451.952506,11659.570422,11851.172109,11618.211729,11990.528224
Minnesota,8143.721235,8481.132938,8816.711410,8934.344177,9023.682594,9738.944105,10275.835155,10582.571737,10792.889229,10690.906044,10582.089722,10831.360472
Mississippi,5028.870718,5110.175722,5218.723833,5450.202007,5367.338919,5487.852891,5795.277651,5992.706076,6415.732532,6707.111424,6870.364318,7147.271234
Missouri,7477.153305,7659.156776,7653.346457,7842.470619,7842.151952,7995.730737,7959.475595,8118.093811,8276.180381,8268.235852,8409.015450,8564.109743
Montana,5629.915903,6006.654923,6166.303351,6074.620778,5789.391646,6078.528495,6143.388398,6212.428068,6411.565795,6360.145986,6301.408098,6351.076487
Nebraska,5947.449208,6475.657666,6132.293690,6394.277360,6462.072085,6908.577327,7224.940026,7295.192695,7483.458761,7473.389998,7347.860887,7607.965866
Nevada,3621.391742,3687.289795,4274.662555,4523.312492,4770.606272,5034.595251,5821.550160,6383.557697,6656.361565,6525.296229,6437.625562,6667.235802
New Hampshire,10187.526874,10484.165486,10703.661219,11111.216956,11167.580249,12273.418976,13077.141447,14262.915112,15224.213501,14968.851124,14755.910446,15159.895264
New Jersey,10053.961278,10504.928628,10942.901592,11427.436371,11661.240894,12337.695121,12752.019146,12707.959473,12934.591792,12998.211641,13027.171713,13303.419490
New Mexico,4925.546389,5187.121484,4756.661543,4867.029246,4904.057391,5303.890133,5613.559463,5741.293411,5914.682467,6089.422281,6165.582904,6354.521439
New York,6234.741246,6114.134719,5911.817268,5815.687489,5556.123429,6361.121889,6341.526905,6553.630970,6835.531235,7076.293108,7305.822053,7643.525100
North Carolina,4493.348279,4464.075589,4769.561759,4933.481152,4764.096461,5030.162414,5827.023600,6009.607767,6459.483265,6657.225808,6684.522510,6973.066092
North Dakota,5803.803189,6197.187288,6464.181071,6648.627758,6625.902320,7020.506475,7191.004702,7247.656687,7298.038987,7431.147839,7526.614430,7687.698217
Ohio,10377.934353,10186.406343,9903.031117,9695.103927,9194.022640,9425.320848,9913.493466,9980.448969,10175.170543,10156.820922,10103.813578,10195.895607
Oklahoma,4454.286642,4638.730256,5197.614388,5720.592520,6120.307023,6007.603094,6294.455326,6413.135657,6669.903459,6725.540172,7093.635560,7449.698064
Oregon,6578.735660,6631.991914,6539.236875,6812.466078,6769.118156,7653.294036,8137.909720,8444.507733,8658.478455,8786.486343,8949.344585,9371.346120
Pennsylvania,10394.175533,10556.225803,10614.532452,11218.914873,11232.678356,11928.765857,12403.908399,12766.059038,12892.924427,13079.198736,13157.057396,13394.777550
Rhode Island,7475.893252,7864.345476,7959.433405,8273.262285,8383.551208,9423.104430,10201.396379,10578.346314,11376.232340,11131.515591,10977.287114,11390.118397
South Carolina,8330.209050,9019.753275,9279.946447,9590.843178,9907.931880,10550.153378,11015.844164,10939.619975,11191.854250,11407.373715,11469.805566,11816.025925
South Dakota,5478.709567,5609.712497,5827.379489,6121.595401,6182.150225,6683.610821,6916.238043,7175.824497,7695.962323,7809.311143,7713.289486,8054.912800
Tennessee,5425.787350,5817.343920,5832.070477,6146.801296,6169.130603,6757.860850,7139.554371,7574.070608,7995.967351,8210.001644,8940.602953,9263.479111
Texas,6394.767951,6577.030655,7018.890369,7389.910226,7506.896701,8120.958398,8477.262964,8506.832721,8691.812347,8705.020332,8852.042784,9116.732643
Utah,4125.412862,4376.137574,4475.202280,4650.487691,4638.240121,5067.841533,5381.485631,5598.685387,5845.931315,6041.942033,6171.257825,6362.682377
Vermont,11067.043728,11295.149396,11472.983204,12012.900576,12304.627184,13316.244011,13655.136649,13832.978329,14088.777804,14266.889917,14501.022155,14993.026533
Virginia,7029.834562,7356.259171,7688.528865,8029.223389,8225.145815,8794.749706,9643.105559,10072.351918,10313.714531,10590.452593,11202.400339,11818.692853
Washington,6191.899451,6414.589601,6649.475086,6858.294978,6979.602035,8113.200932,8973.156575,10029.041333,11036.643315,11045.088075,10703.371502,10288.352636
West Virginia,4575.251711,4727.889632,4885.663705,5048.053404,5106.946491,5518.882754,5720.838875,5847.985340,6130.311081,6388.324628,6697.955282,7171.450966
Wisconsin,6574.955502,6871.378731,7085.736943,7347.518493,7373.445582,7944.753105,8441.138264,8658.947947,9052.235055,8930.733967,8785.102914,8815.260668
Wyoming,4086.351225,4188.047932,4122.205455,4071.897820,3928.670755,4129.188181,4298.839315,4357.467400,4456.324691,4499.358790,4653.877970,4890.999758

We now need to add a column that contains the average of each row.

In [9]:
df['Average'] = df.mean(axis=1)

/tmp/ipykernel_23488/344794366.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['Average'] = df.mean(axis=1)

To shorten the large values for each column, we will turn each value into an int.

In [17]:
df = df.astype({"2004-05": "int", "2005-06": "int", "2006-07": "int", "  2007-08 ": "int", "2008-09": "int", "2009-10": "int", "2010-11": "int", "2011-12": "int", "2012-13": "int", "2013-14": "int", "2014-15": "int", "2015-16": "int", "Average": "int"})

In [19]:
df.head(10)

,State,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,Average
0,Alabama,5682,5840,5753,6008,6475,7188,8071,8451,9098,9358,9496,9751,7598
1,Alaska,4328,4632,4918,5069,5075,5454,5759,5762,6026,6012,6148,6571,5479
2,Arizona,5138,5415,5481,5681,6058,7263,8839,9966,10133,10296,10413,10646,7944
3,Arkansas,5772,6082,6231,6414,6416,6627,6900,7028,7286,7408,7606,7867,6803
4,California,5285,5527,5334,5672,5897,7258,8193,9436,9360,9274,9186,9269,7474
5,Colorado,4703,5406,5596,6227,6284,6948,7748,8315,8792,9292,9298,9748,7363
6,Connecticut,7983,8249,8367,8677,8720,9371,9827,9736,10036,10453,10663,11397,9457
7,Delaware,8352,8610,8681,8945,8995,9987,10534,11026,11362,11502,11514,11676,10099
8,Florida,3848,3924,3887,3879,4150,4783,5510,5940,6494,6451,6344,6360,5131
9,Georgia,4298,4492,4584,4790,4831,5549,6428,7709,7853,7992,8063,8446,6253

In [ ]:
df.to_csv("us_avg_tuition.csv")

Other pre-processing was applied to our dataset such as manually changing the id of each state to that corresponding state's FIPS code. This allows the states to be shown on the map with their corresponding values.